# Generated by Django 4.1.7 on 2023-03-31 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0005_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
